version: '3.9'
services:
  tg_bot:
    container_name: tg_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: ["sh", "-c", "alembic -c ./alembic.ini upgrade head && python app/main.py"]
    networks:
      - imei-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.0-bookworm
    container_name: postgres_container
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
      PGDATABASE: ${POSTGRES_DB_NAME}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/imeicheck/postgresql/imeicheck
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

    networks:
      - imei-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:

networks:
  imei-network:
    driver: bridge