"""Initial migration

Revision ID: ae6f16475d61
Revises: 
Create Date: 2025-01-27 05:23:03.394496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.main import settings

# revision identifiers, used by Alembic.
revision: str = "ae6f16475d61"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    white_list = settings.WHITE_LIST.split(",")

    for tg_id in white_list:
        op.execute(
            sa.text(f"INSERT INTO users (user_id) VALUES (:user_id)").params(
                {"user_id": tg_id}
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
